spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: false

logging:
  level:
    root: INFO
    com.example.muneoserver: INFO

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
